spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: admin
    password: 1234
jwt:
  secret: yourVerySecretKeyForTabulariumProject2026SpecificLongEnough
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000